/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiPublicWebhookRazorpayRouteImport } from './routes/api/public/webhook/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRazorpayRoute =
  ApiPublicWebhookRazorpayRouteImport.update({
    id: '/api/public/webhook/razorpay',
    path: '/api/public/webhook/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/report/$id' | '/api/public/webhook/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/report/$id' | '/api/public/webhook/razorpay'
  id: '__root__' | '/' | '/report/$id' | '/api/public/webhook/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiPublicWebhookRazorpayRoute: typeof ApiPublicWebhookRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/razorpay': {
      id: '/api/public/webhook/razorpay'
      path: '/api/public/webhook/razorpay'
      fullPath: '/api/public/webhook/razorpay'
      preLoaderRoute: typeof ApiPublicWebhookRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportIdRoute: ReportIdRoute,
  ApiPublicWebhookRazorpayRoute: ApiPublicWebhookRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
