/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiPublicWebhookRazorpayRouteImport } from './routes/api/public/webhook/razorpay'
import { Route as ApiPublicReportIdOgImageRouteImport } from './routes/api/public/report/$id/og-image'
import { Route as ApiPublicReportIdPdfRouteImport } from './routes/api/public/report/$id/pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRazorpayRoute =
  ApiPublicWebhookRazorpayRouteImport.update({
    id: '/api/public/webhook/razorpay',
    path: '/api/public/webhook/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReportIdOgImageRoute =
  ApiPublicReportIdOgImageRouteImport.update({
    id: '/api/public/report/$id/og-image',
    path: '/api/public/report/$id/og-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReportIdPdfRoute = ApiPublicReportIdPdfRouteImport.update({
  id: '/api/public/report/$id/pdf',
  path: '/api/public/report/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
  '/api/public/report/$id/og-image': typeof ApiPublicReportIdOgImageRoute
  '/api/public/report/$id/pdf': typeof ApiPublicReportIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
  '/api/public/report/$id/og-image': typeof ApiPublicReportIdOgImageRoute
  '/api/public/report/$id/pdf': typeof ApiPublicReportIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
  '/api/public/report/$id/og-image': typeof ApiPublicReportIdOgImageRoute
  '/api/public/report/$id/pdf': typeof ApiPublicReportIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/report/$id'
    | '/api/public/webhook/razorpay'
    | '/api/public/report/$id/og-image'
    | '/api/public/report/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/report/$id'
    | '/api/public/webhook/razorpay'
    | '/api/public/report/$id/og-image'
    | '/api/public/report/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/report/$id'
    | '/api/public/webhook/razorpay'
    | '/api/public/report/$id/og-image'
    | '/api/public/report/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiPublicWebhookRazorpayRoute: typeof ApiPublicWebhookRazorpayRoute
  ApiPublicReportIdOgImageRoute: typeof ApiPublicReportIdOgImageRoute
  ApiPublicReportIdPdfRoute: typeof ApiPublicReportIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/razorpay': {
      id: '/api/public/webhook/razorpay'
      path: '/api/public/webhook/razorpay'
      fullPath: '/api/public/webhook/razorpay'
      preLoaderRoute: typeof ApiPublicWebhookRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report/$id/og-image': {
      id: '/api/public/report/$id/og-image'
      path: '/api/public/report/$id/og-image'
      fullPath: '/api/public/report/$id/og-image'
      preLoaderRoute: typeof ApiPublicReportIdOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report/$id/pdf': {
      id: '/api/public/report/$id/pdf'
      path: '/api/public/report/$id/pdf'
      fullPath: '/api/public/report/$id/pdf'
      preLoaderRoute: typeof ApiPublicReportIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReportIdRoute: ReportIdRoute,
  ApiPublicWebhookRazorpayRoute: ApiPublicWebhookRazorpayRoute,
  ApiPublicReportIdOgImageRoute: ApiPublicReportIdOgImageRoute,
  ApiPublicReportIdPdfRoute: ApiPublicReportIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
