// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tipbzrjneouuyxdzwwst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcGJ6cmpuZW91dXl4ZHp3d3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0MzQzOTEsImV4cCI6MjA4MTAxMDM5MX0.omVJL2uT91jSqhfqeNBV4EcGUmfaYBgTh1b4jGh5EIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});